added compatibility with Bubble_StockMovements
shopgate/cart-integration-magento pull request #7
Opened 2017-12-19 16:33 UTC by sprankhub

https://github.com/jreinke/magento-stock-movements

2018-01-16 08:33 UTC, augsteyer requested changes

2018-01-16 08:33 UTC, augsteyer commented on src/app/code/community/Shopgate/Framework/Model/Cataloginventory/Stock.php
> +if (Mage::helper('core')->isModuleEnabled('Bubble_StockMovements')) {
Please use ```Mage::getConfig()->getModuleConfig(‘ Bubble_StockMovements’)->is(‘active’, ‘true’)``` as isModuleEnabled is not supported in versions CE 1.4.0.0, 1.4.0.1

2018-01-16 09:19 UTC, sprankhub commented
@augsteyer please do not support Magento 1.4 :D Anyway, fixed.

2018-01-16 09:28 UTC, augsteyer commented
that's funny, that's why pushing this fix is going so long. We are considering dropping 1.4 support, then your modifications will not be needed anymore as this class rewrite is for 1.4 specifically :)

2018-01-25 06:40 UTC, sprankhub commented
What is the current status here?

2018-01-26 10:27 UTC, merged